# Generated by Django 5.1.3 on 2025-09-14 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_unique_together_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
