# Generated by Django 5.1.3 on 2025-09-15 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_proposal_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='projects/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
