# Generated by Django 5.1.3 on 2025-09-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_user_alter_proposal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='catatan',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
