# Generated by Django 5.1.3 on 2025-09-17 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
