# Generated by Django 5.1.3 on 2025-09-17 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_proposal_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reviewer_1',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Reviewer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_1_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer 1'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewer_2',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Reviewer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_2_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer 2'),
        ),
    ]
