# Generated by Django 5.1.3 on 2025-09-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_proposal_reviewer_1_proposal_reviewer_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='reviewer_1',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='reviewer_2',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision', 'Revision')], default='pending', max_length=25),
        ),
    ]
