# Generated by Django 5.1.3 on 2025-09-18 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_remove_proposal_reviewer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='reviewer1',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Reviewer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_1_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='reviewer2',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Reviewer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_2_proposals', to=settings.AUTH_USER_MODEL),
        ),
    ]
