# Generated by Django 5.1.3 on 2025-09-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_proposal_reviewer1_proposal_reviewer2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='reviewer1',
            new_name='reviewer_1',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='reviewer2',
            new_name='reviewer_2',
        ),
    ]
