# Generated by Django 5.1.3 on 2025-09-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_rename_reviewer1_proposal_reviewer_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='catatan_2',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
